name: Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Build docker image
              run: |
                docker build -t demo-website:${{ github.sha }} .
            
            - name: Save docker image as tar
              run: |
                docker save demo-website:${{ github.sha }} -o demo-website.tar

            - name: Copy docker image to droplet
              uses: appleboy/scp-actions@v0.1.7
              with: 
                host: ${{secrets.HOST}}
                username: ${{secrets.USERNAME}}
                key: ${{secrets.KEY}}
                source: demo-server.tar
                target: ~/images

            - name: Load the docker image run
              uses: appleboy/ssh-actions@v1.0.3
              with:
                host: ${{secrets.HOST}}
                username: ${{secrets.USERNAME}}
                key: ${{secrets.KEY}}
                script: |
                  docker load -i /root/images/demo-website.tar
                  docker rm -f demo-server
                  docker run -d -p 8000:8000 --name demo-website demo-website:${{ github.sha }}
